networks:
  stream-rec:

services:
  # Backend service
  backend:
    #   Uses the latest main branch image
    image: streamrec/stream-rec:latest
    #    container name, you can change it to any name you like
    container_name: stream-rec
    restart: unless-stopped
    #    port mapping, you can change the port to any port you like
    ports:
      - "12555:12555"
    networks:
      - stream-rec
    volumes:
      # Host machine path binding to container path, storage path mapping
      - "./downloads:/opt/records" // [!code highlight]
      # Rclone configuration file path binding
      - "./rclone:/root/.config/rclone" // [!code highlight]
    environment:
      # Timezone, by default is Europe/Paris.
      - TZ=Europe/Paris
      # Proxy settings, comment it out if you don't need a proxy.
      #- HTTP_PROXY=http://192.168.110.10:7890
      # Log level, by default is info. `DEBUG` logs are useful for debugging, but they can be very verbose.
      - LOG_LEVEL=INFO
      # CONTAINER database path
      - DB_PATH=/opt/records
      # CONTAINER download path for the first initialization
      - DOWNLOAD_PATH=/opt/records
      # FIRST USE LOGIN secret, YOU CAN CHANGE IT TO ANY STRING YOU LIKE
      - LOGIN_SECRET=123 // [!code highlight]
      # Group ID
      - PGID=1000
      # User ID
      - PUID=1000

  # Frontend service
  frontend:
    #   Uses the latest main branch image
    image: streamrec/stream-rec-front:latest
    container_name: stream-rec-frontend
    restart: unless-stopped
    #   port mapping, you can change the port to any port you like
    ports:
      - "15275:15275"
    networks:
      - stream-rec
    depends_on:
      - backend
    environment:
      #    timezone, by default is Europe/Paris.
      - TZ=Europe/Paris
      # Backend api url, made up of the container name and port.
      # DO NOT CHANGE IT if you don't know what you are doing.
      # Make sure the port is the same as the backend port. // [!code warning]
      - API_URL=http://backend:12555/api
      # Secret for next-auth, YOU CAN CHANGE IT TO ANY STRING YOU LIKE
      - AUTH_SECRET=6chtw8GBN3BO // [!code highlight]
      # CLIENT url, used by next-auth to redirect to login page.
      # Should be the address which the user types in the browser to access the frontend.
      # Make sure the port is the same as the frontend port. // [!code warning]
      # - AUTH_URL=http://localhost:15275/
      # Domain base url. Used for next-auth redirect login page.
      # - NEXT_PUBLIC_BASE_URL=https://abc.xyz
      # Domain custom path, no need to fill if not required.
      # - NEXT_PUBLIC_BASE_PATH=/webui
      # Whether there is a reverse proxy, such as NGINX. It is recommended to turn it on, NEXT_AUTH currently has a bug.
      - AUTH_TRUST_HOST=true
      # WS_API_URL, CLIENT websocket url. Used for live status updates.
      # This should use the ip address of the deployed server.
      # Below is an example of using localhost, you can change it to the ip address of the deployed server.
      # For example, if backend is deployed on the server ip address 12.12.12.12, with port 12555, then you should change it to ws://12.12.12.12:12555/live/update
      - WS_API_URL=ws://localhost:12555/live/update